services:
  python_server:
    build: ./llm_assignment
    container_name: python_server
    volumes:
      - ./llm_assignment:/app
    ports:
      - "5000:5000"
    command: ${PYTHON_COMMAND}
    env_file:
      - .env

  node_server:
    build: ./node_api_server
    container_name: node_server
    volumes:
      - ./node_api_server:/app
    ports:
      - "3000:3000"
    command: ${NODE_COMMAND}
    depends_on:
      - python_server
    env_file:
      - .env
