import os

class Config:
    LLAMA2_MODEL_PATH = os.getenv('LLAMA2_MODEL_PATH', '')
    LLAMA2_TOKENIZER_PATH = os.getenv('LLAMA2_TOKENIZER_PATH', '')
    MISTRAL_MODEL_PATH = os.getenv('MISTRAL_MODEL_PATH', '')
    MISTRAL_TOKENIZER_PATH = os.getenv('MISTRAL_TOKENIZER_PATH', '')
